[package]
name = "log_lib"
version = "0.1.0"
edition = "2024"


[lib]
name = "log_lib"
crate-type = ["staticlib", "cdylib"]


[dependencies]
chrono = "0.4.41"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
simply_colored = "0.1.0"
